DarkMode UI
Pomodorify/Pomodorify pull request #5
Opened 2024-05-12 21:29 UTC by TomaszJarzabek15

New color theme added for dark mode, minor UI changes to make the app more functional on different screen sizes, mainly pomodoro and settings fragments xmls affected. Please review.

2024-05-12 21:59 UTC, NorbertKoziana requested changes
Great effort! Please make the necessary adjustments.

2024-05-12 21:59 UTC, NorbertKoziana commented on app/src/main/java/com/example/pomodorify/Settings.java
> +import androidx.appcompat.app.AppCompatActivity;
This line is not needed.

2024-05-12 21:59 UTC, NorbertKoziana commented on app/src/main/java/com/example/pomodorify/Settings.java
> +                // if the above condition turns false
Remove this comment (I think the code is readable enough that it doesn't need commenting) or atleast write it in one line and thus make the if - else structure more readable.

2024-05-13 09:21 UTC, TomaszJarzabek15 reviewed
Changed the mentioned parts in the review

2024-05-13 09:22 UTC, merged